[platformio]
default_envs = ota

[env]
platform = espressif32
board = wt32-eth01
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
  olikraus/U8g2 @ ^2.36.6
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -I include

[env:serial]
upload_protocol = esptool

[env:ota]
upload_protocol = espota
upload_port = 192.168.1.112
upload_flags =
  --port=3232
  --auth=moje_haslo_ota
