[platformio]
default_envs = ota

[env]
platform = espressif32
board = wt32-eth01
framework = arduino
monitor_speed = 115200

[env:serial]
upload_protocol = esptool

[env:ota]
upload_protocol = espota
upload_port = 192.168.1.100
upload_flags =
    --port=3232
    --auth=moje_haslo_ota